/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidadejemplo.vistas;

import java.time.LocalDate;
import java.time.ZoneId;
import javax.swing.JOptionPane;
import universidadejemplo.accesoADatos.AlumnoData;
import universidadejemplo.entidades.Alumno;

/**
 *
 * @author borch
 */
public class GestionAlumno extends javax.swing.JInternalFrame {

   //  private Alumno alum = new Alumno();
   
    /**
     * Creates new form cargarAlumno
     */
    public GestionAlumno() {
        initComponents();
        this.setSize(500,500);
        this.setTitle("Sistema de gestión ALUMNOS");
             
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jRBestado = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jTFDni = new javax.swing.JTextField();
        jTFapellido = new javax.swing.JTextField();
        jTFnombre = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jBbuscarAlum = new javax.swing.JButton();
        jBguardarAlum = new javax.swing.JButton();
        jBeliminarAlum = new javax.swing.JButton();
        jLidAlumno = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Sistema de gestión de Alumnos");
        setPreferredSize(new java.awt.Dimension(360, 380));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Ingresar documento del alumno:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Apellido:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Estado:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Fecha de nacimiento:");

        jBbuscarAlum.setText("Buscar");
        jBbuscarAlum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBbuscarAlumActionPerformed(evt);
            }
        });

        jBguardarAlum.setText("Guardar");
        jBguardarAlum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBguardarAlumActionPerformed(evt);
            }
        });

        jBeliminarAlum.setText("Eliminar");
        jBeliminarAlum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBeliminarAlumActionPerformed(evt);
            }
        });

        jLidAlumno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLidAlumno.setText("ID Alumno : ");

        jButton1.setText("Nueva consulta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBeliminarAlum)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBguardarAlum))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1)
                                    .addComponent(jLidAlumno)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(108, 108, 108)
                                        .addComponent(jButton1)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTFDni, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBbuscarAlum)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTFapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTFnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jRBestado)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTFDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLidAlumno)
                .addGap(17, 17, 17)
                .addComponent(jBbuscarAlum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRBestado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBguardarAlum)
                    .addComponent(jBeliminarAlum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBbuscarAlumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBbuscarAlumActionPerformed
        // TODO add your handling code here:
        int dni;
        String doc =jTFDni.getText();
        
      // Verifica si el campo de texto está vacío  
        if(doc.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Por favor ingrese un DNI valido");
        return;
        }
        try{
      // valor del campo de texto a un entero
            dni=Integer.parseInt(doc);
            if(doc.length()!=8){
                JOptionPane.showMessageDialog(null,"El dni debe tener ocho digitos");
                return;
            }
        }catch (NumberFormatException ex){
            JOptionPane.showMessageDialog(null, "El dni debe ser un numero entero");
            return;
        }
     // Debe devolver los datos en los TextField para poder 
     // eliminarlos, ver los datos.
         Alumno estudiante = new AlumnoData().buscarAlumnoPorDni(dni);
         if (estudiante!=null){
          jTFapellido.setText(estudiante.getApellido());
          jTFnombre.setText(estudiante.getNombre());
         
         //devuelve fecha en el Chooser
          LocalDate fechaNacimiento=estudiante.getFechaNacimiento();
          java.util.Date fechaUtil=java.sql.Date.valueOf(fechaNacimiento);
          
          jDateChooser1.setDate(fechaUtil);
        
      // Configurar estado en rbutton    
          jRBestado.setSelected(estudiante.isEstado());
          
      // Configurar ID en el campo Jlabel  
          jLidAlumno.setText("ID Alumno "+ estudiante.getIdAlumno());
     
     // Habilitar el botón "Eliminar" una vez que se encuentra un alumno
          jBeliminarAlum.setEnabled(true);     
        }else{
            JOptionPane.showMessageDialog(null,"No se encontro al alumno");
        }
    }//GEN-LAST:event_jBbuscarAlumActionPerformed

    private void jBguardarAlumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBguardarAlumActionPerformed
        // TODO add your handling code here:
    //Obtengo los datos del formulario:
       int dni = Integer.parseInt(jTFDni.getText());
       String apellido = jTFapellido.getText();
       String nombre = jTFnombre.getText();
       LocalDate fechaNacimiento = jDateChooser1.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
       boolean estado = jRBestado.isSelected();
    
       //obj alumno
       Alumno alumno = new Alumno(dni, apellido, nombre, fechaNacimiento, estado);
       //Invoco al metodo para guardar el alumno en la BD. 
       AlumnoData alum = new AlumnoData();
       alum.guardarAlumno(alumno);
       
       // Limpio los campos de texto:
       jTFDni.setText("");
       jTFapellido.setText("");
       jTFnombre.setText("");
       jDateChooser1.setDate(null);
       jRBestado.setSelected(false);
        
        
        
    }//GEN-LAST:event_jBguardarAlumActionPerformed

    
    private void jBeliminarAlumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBeliminarAlumActionPerformed
        // TODO add your handling code here:
      String idAlumnoText = jLidAlumno.getText().replace("ID Alumno", "").trim();
      
      if (idAlumnoText.isEmpty()){
              JOptionPane.showMessageDialog(null, "El ID del alumno no es válido.");
        return; 
      }
      
      int idAlumno = Integer.parseInt(idAlumnoText);
      
      AlumnoData alumnoData = new AlumnoData();
     //Se muestra un diálogo de confirmación antes de eliminar Alumno
     int respuesta= JOptionPane.showConfirmDialog(null,"Realmente desea eliminar al alumno?");
     if(respuesta==0){
         alumnoData.eliminarAlumno(idAlumno);
     }
         jTFDni.setText("");
         jTFapellido.setText("");
         jTFnombre.setText("");
         jDateChooser1.setDate(null);
         jRBestado.setSelected(false);
         
      //Desactiva el boton eliminar. 
         jBeliminarAlum.setEnabled(false);
    
    }//GEN-LAST:event_jBeliminarAlumActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         jLidAlumno.setText("");
         jTFDni.setText("");
         jTFnombre.setText("");
         jTFapellido.setText("");
         jRBestado.setSelected(false); 
         jDateChooser1.setDate(null);
    }//GEN-LAST:event_jButton1ActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBbuscarAlum;
    private javax.swing.JButton jBeliminarAlum;
    private javax.swing.JButton jBguardarAlum;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLidAlumno;
    private javax.swing.JRadioButton jRBestado;
    private javax.swing.JTextField jTFDni;
    private javax.swing.JTextField jTFapellido;
    private javax.swing.JTextField jTFnombre;
    // End of variables declaration//GEN-END:variables
}
