/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidadejemplo.vistas;

import javax.swing.JOptionPane;
import universidadejemplo.accesoADatos.MateriaData;
import universidadejemplo.entidades.Materia;

/**
 *
 * @author borch
 */
public class GestionMateria extends javax.swing.JInternalFrame {
private MateriaData materiaData;
    /**
     * Creates new form GestionMateria
     */
    public GestionMateria() {
        initComponents();
        this.setSize(500, 500);
        this.setTitle("Sistema de gestión de MATERIAS");
     
        materiaData = new MateriaData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jRBestadoMateria = new javax.swing.JRadioButton();
        jTFcodigo = new javax.swing.JTextField();
        jTFnomMateria = new javax.swing.JTextField();
        jTFanio = new javax.swing.JTextField();
        jBbuscarMateria = new javax.swing.JButton();
        jBEliminar = new javax.swing.JButton();
        jBguardar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jBnuevConsulta = new javax.swing.JButton();

        setClosable(true);
        setTitle("Sistema de gestión de MATERIAS");
        setPreferredSize(new java.awt.Dimension(360, 380));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Año:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Estado:");

        jBbuscarMateria.setText("Buscar");
        jBbuscarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBbuscarMateriaActionPerformed(evt);
            }
        });

        jBEliminar.setText("Eliminar");
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });

        jBguardar.setText("Guardar");
        jBguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBguardarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Ingresar el código de la materia :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Información de la materia:");

        jBnuevConsulta.setText("Nueva consulta");
        jBnuevConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnuevConsultaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBbuscarMateria))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBguardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBEliminar))
                            .addComponent(jTFcodigo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRBestadoMateria)
                                .addGap(80, 80, 80))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jTFnomMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTFanio))))))
                .addGap(123, 123, 123))
            .addGroup(layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(jBnuevConsulta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jTFcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBbuscarMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel7)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTFnomMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTFanio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRBestadoMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBguardar)
                    .addComponent(jBEliminar))
                .addGap(18, 18, 18)
                .addComponent(jBnuevConsulta)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private Integer idMat;
    private void jBbuscarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBbuscarMateriaActionPerformed
        // TODO add your handling code here:
    //Obtener ID materia
       int idMateriaBuscar = Integer.parseInt(jTFcodigo.getText());
     
    // Llamar a la función
       Materia mat = materiaData.buscarMateria(idMateriaBuscar);
    
    if (mat != null){
        idMat= mat.getIdMateria();
        jTFnomMateria.setText(mat.getNombre());
        jTFanio.setText(String.valueOf(mat.getAnioMateria()));
    }else{
        idMat=null;
        JOptionPane.showMessageDialog(null,"No se encontró la materia.");
    }
    }//GEN-LAST:event_jBbuscarMateriaActionPerformed

    // Variable para almacenar el ID de la materia
    private Integer idMateria;
    
    private void jBguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBguardarActionPerformed
        // TODO add your handling code here:
    //Obtener datos 
        String nombreMateria = jTFnomMateria.getText();
        int anioMateria = Integer.parseInt((jTFanio.getText()));
    
    //Verifico
        if (idMat != null){
            //Modifica materia existente
            Materia materia = new Materia(idMat,nombreMateria,anioMateria,true);
            materiaData.modificarMateria(materia);
        }else{
            //Guarda nueva materia
            Materia materia = new Materia(nombreMateria, anioMateria, true);
            materiaData.guardarMateria(materia);
        }
        
      jTFnomMateria.setText("");
      jTFanio.setText("");
      jTFcodigo = null; 
    }//GEN-LAST:event_jBguardarActionPerformed

    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed
        // TODO add your handling code here:
        int idMateriaEliminar = Integer.parseInt(jTFcodigo.getText());
        int respuesta= JOptionPane.showConfirmDialog(null,"Realmente desea eliminar la materia?");
     if(respuesta==0){
        materiaData.eliminarMateria(idMateriaEliminar);
        JOptionPane.showMessageDialog(null, "Materia eliminada");
     }
      jTFnomMateria.setText("");
      jTFanio.setText("");
      jTFcodigo = null; 
    }//GEN-LAST:event_jBEliminarActionPerformed

    private void jBnuevConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnuevConsultaActionPerformed
        // TODO add your handling code here:
        jTFcodigo.setText("");
        jTFnomMateria.setText("");
        jTFanio.setText("");
        jRBestadoMateria.setSelected(false);
    }//GEN-LAST:event_jBnuevConsultaActionPerformed
   


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBbuscarMateria;
    private javax.swing.JButton jBguardar;
    private javax.swing.JButton jBnuevConsulta;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRBestadoMateria;
    private javax.swing.JTextField jTFanio;
    private javax.swing.JTextField jTFcodigo;
    private javax.swing.JTextField jTFnomMateria;
    // End of variables declaration//GEN-END:variables
}
